// <auto-generated />
using System;
using APISimplesNacional.Infra.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APISimplesNacional.Infra.Migrations
{
    [DbContext(typeof(SimplesNacionalDbContext))]
    [Migration("20250519004341_AddIrDependenteToEmpresas")]
    partial class AddIrDependenteToEmpresas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APISimplesNacional.Infra.Entidades.AnexoIII", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Aliquota")
                        .HasColumnType("numeric");

                    b.Property<int>("Faixa")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<decimal>("LimiteFin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LimiteInic")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VlrDeduzir")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("AnexoIII");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aliquota = 0.06m,
                            Faixa = 1,
                            IdEmpresa = 1,
                            LimiteFin = 180000m,
                            LimiteInic = 0m,
                            VlrDeduzir = 0m
                        },
                        new
                        {
                            Id = 2,
                            Aliquota = 0.112m,
                            Faixa = 2,
                            IdEmpresa = 1,
                            LimiteFin = 360000m,
                            LimiteInic = 180000.01m,
                            VlrDeduzir = 9360m
                        },
                        new
                        {
                            Id = 3,
                            Aliquota = 0.135m,
                            Faixa = 3,
                            IdEmpresa = 1,
                            LimiteFin = 720000m,
                            LimiteInic = 360000.01m,
                            VlrDeduzir = 17640m
                        },
                        new
                        {
                            Id = 4,
                            Aliquota = 0.16m,
                            Faixa = 4,
                            IdEmpresa = 1,
                            LimiteFin = 1800000m,
                            LimiteInic = 720000.01m,
                            VlrDeduzir = 35640m
                        },
                        new
                        {
                            Id = 5,
                            Aliquota = 0.205m,
                            Faixa = 5,
                            IdEmpresa = 1,
                            LimiteFin = 3600000m,
                            LimiteInic = 1800000.01m,
                            VlrDeduzir = 125640m
                        },
                        new
                        {
                            Id = 6,
                            Aliquota = 0.33m,
                            Faixa = 6,
                            IdEmpresa = 1,
                            LimiteFin = 4800000m,
                            LimiteInic = 3600000.01m,
                            VlrDeduzir = 648000m
                        });
                });

            modelBuilder.Entity("APISimplesNacional.Infra.Entidades.AnexoV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Aliquota")
                        .HasColumnType("numeric");

                    b.Property<int>("Faixa")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<decimal>("LimiteFin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LimiteInic")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VlrDeduzir")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("AnexoV");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aliquota = 0.15m,
                            Faixa = 1,
                            IdEmpresa = 1,
                            LimiteFin = 180000m,
                            LimiteInic = 0m,
                            VlrDeduzir = 0m
                        },
                        new
                        {
                            Id = 2,
                            Aliquota = 0.18m,
                            Faixa = 2,
                            IdEmpresa = 1,
                            LimiteFin = 360000m,
                            LimiteInic = 180000.01m,
                            VlrDeduzir = 4500m
                        },
                        new
                        {
                            Id = 3,
                            Aliquota = 0.195m,
                            Faixa = 3,
                            IdEmpresa = 1,
                            LimiteFin = 720000m,
                            LimiteInic = 360000.01m,
                            VlrDeduzir = 9900m
                        },
                        new
                        {
                            Id = 4,
                            Aliquota = 0.205m,
                            Faixa = 4,
                            IdEmpresa = 1,
                            LimiteFin = 1800000m,
                            LimiteInic = 720000.01m,
                            VlrDeduzir = 17100m
                        },
                        new
                        {
                            Id = 5,
                            Aliquota = 0.23m,
                            Faixa = 5,
                            IdEmpresa = 1,
                            LimiteFin = 3600000m,
                            LimiteInic = 1800000.01m,
                            VlrDeduzir = 62100m
                        },
                        new
                        {
                            Id = 6,
                            Aliquota = 0.305m,
                            Faixa = 6,
                            IdEmpresa = 1,
                            LimiteFin = 4800000m,
                            LimiteInic = 3600000.01m,
                            VlrDeduzir = 540m
                        });
                });

            modelBuilder.Entity("APISimplesNacional.Infra.Entidades.Empresas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("IrDependente")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Empresas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Celular = "(62)99213-7872",
                            Email = "julianops79@gmail.com",
                            IrDependente = 0m,
                            Nome = "JPS Technology in Development"
                        });
                });

            modelBuilder.Entity("APISimplesNacional.Infra.Entidades.ErroLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ErrosLog");
                });

            modelBuilder.Entity("APISimplesNacional.Infra.Entidades.TabelaINSS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Aliquota")
                        .HasColumnType("numeric");

                    b.Property<int>("Faixa")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<decimal>("LimiteFin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LimiteInic")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("TabelaINSS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aliquota = 0.075m,
                            Faixa = 1,
                            IdEmpresa = 1,
                            LimiteFin = 1518m,
                            LimiteInic = 0m
                        },
                        new
                        {
                            Id = 2,
                            Aliquota = 0.09m,
                            Faixa = 2,
                            IdEmpresa = 1,
                            LimiteFin = 2793.88m,
                            LimiteInic = 1518.01m
                        },
                        new
                        {
                            Id = 3,
                            Aliquota = 0.12m,
                            Faixa = 3,
                            IdEmpresa = 1,
                            LimiteFin = 4190.83m,
                            LimiteInic = 2793.89m
                        },
                        new
                        {
                            Id = 4,
                            Aliquota = 0.14m,
                            Faixa = 4,
                            IdEmpresa = 1,
                            LimiteFin = 8157.41m,
                            LimiteInic = 4190.84m
                        });
                });

            modelBuilder.Entity("APISimplesNacional.Infra.Entidades.TabelaIR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Aliquota")
                        .HasColumnType("numeric");

                    b.Property<int>("Faixa")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<decimal>("LimiteFin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LimiteInic")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VlrDeduzir")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("TabelaIR");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aliquota = 0m,
                            Faixa = 1,
                            IdEmpresa = 1,
                            LimiteFin = 3036m,
                            LimiteInic = 0m,
                            VlrDeduzir = 0m
                        },
                        new
                        {
                            Id = 2,
                            Aliquota = 0.075m,
                            Faixa = 2,
                            IdEmpresa = 1,
                            LimiteFin = 3533.31m,
                            LimiteInic = 3036m,
                            VlrDeduzir = 169.44m
                        },
                        new
                        {
                            Id = 3,
                            Aliquota = 0.15m,
                            Faixa = 3,
                            IdEmpresa = 1,
                            LimiteFin = 4688.85m,
                            LimiteInic = 3533.31m,
                            VlrDeduzir = 381.44m
                        },
                        new
                        {
                            Id = 4,
                            Aliquota = 0.225m,
                            Faixa = 4,
                            IdEmpresa = 1,
                            LimiteFin = 5830.85m,
                            LimiteInic = 4688.85m,
                            VlrDeduzir = 662.77m
                        },
                        new
                        {
                            Id = 5,
                            Aliquota = 0.275m,
                            Faixa = 5,
                            IdEmpresa = 1,
                            LimiteFin = 99999999m,
                            LimiteInic = 5830.85m,
                            VlrDeduzir = 896m
                        });
                });

            modelBuilder.Entity("APISimplesNacional.Infra.Entidades.AnexoIII", b =>
                {
                    b.HasOne("APISimplesNacional.Infra.Entidades.Empresas", "Empresa")
                        .WithMany("AnexosIII")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("APISimplesNacional.Infra.Entidades.AnexoV", b =>
                {
                    b.HasOne("APISimplesNacional.Infra.Entidades.Empresas", "Empresa")
                        .WithMany("AnexosV")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("APISimplesNacional.Infra.Entidades.TabelaINSS", b =>
                {
                    b.HasOne("APISimplesNacional.Infra.Entidades.Empresas", "Empresa")
                        .WithMany("TabelaINSSs")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("APISimplesNacional.Infra.Entidades.TabelaIR", b =>
                {
                    b.HasOne("APISimplesNacional.Infra.Entidades.Empresas", "Empresa")
                        .WithMany("TabelaIRs")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("APISimplesNacional.Infra.Entidades.Empresas", b =>
                {
                    b.Navigation("AnexosIII");

                    b.Navigation("AnexosV");

                    b.Navigation("TabelaINSSs");

                    b.Navigation("TabelaIRs");
                });
#pragma warning restore 612, 618
        }
    }
}
